[project]
name = "alex-seedvr-node"
description = "SeedVR2 Video Upscaler (RunPodSkin Edition by Alex)"
version = "1.0.3"     # ✅ bump version (must be unique for registry)
license = { file = "LICENSE.txt" }
dependencies = ["torch", "opencv-python", "numpy"]

[project.urls]
Repository = "https://github.com/shangeethAlex/alex-seedvr-node"

[tool.comfy]
PublisherId = "runpodskin-alex-v02"
DisplayName = "SeedVR2 Video Upscaler - RunPodSkin Edition"
Icon = "https://raw.githubusercontent.com/shangeethAlex/alex-seedvr-node/nightly/icon.png"
